name: Run Cypress Tests
on:
  push:
  pull_request:
    branches-ignore:
      - ea-deploy
  workflow_dispatch:
jobs:
  buildAndRunCypressTests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14.5-alpine
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10
      mongodb:
        image: mongo:4.4.17
        ports:
          - 27017:27017

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Environment
      id: setup-environment
      uses: ./.github/actions/setupEnvironment

    - name: Setup database template
      env:
        TESTING_DB_URL: mongodb://127.0.0.1:27017/test?retryWrites=true
        PG_URL: postgres://postgres:postgres@localhost:5432/postgres
      run: yarn init-cypress-db-ci

    - name: Cypress run
      uses: cypress-io/github-action@v4
      env:
        TESTING_DB_URL: mongodb://127.0.0.1:27017/test?retryWrites=true
        PG_URL: postgres://postgres:postgres@localhost:5432/postgres
        CYPRESS_CACHE_FOLDER: ${{ steps.setup-environment.outputs.cypress-cache-folder }}
        NODE_OPTIONS: "--max_old_space_size=4096"
      with:
          start: yarn ea-start-testing-db
          command: yarn cypress-run-ci

    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: Upload screenshots
        path: cypress/screenshots

    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: Upload videos
        path: cypress/videos
